# Generated by Django 3.1.3 on 2020-11-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValorSensor',
            new_name='SensorValue',
        ),
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='valor',
            new_name='value',
        ),
    ]
