# Generated by Django 3.1.3 on 2020-11-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20201119_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='nome',
            new_name='name',
        ),
    ]
