# Generated by Django 3.1.3 on 2020-11-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20201119_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensortype',
            field=models.CharField(choices=[('LED', 'Led'), ('WEIGHT', 'Weight'), ('CAMERA', 'Camera'), ('SERVO', 'Servo')], default='Undefined', max_length=20),
        ),
    ]
