# Generated by Django 3.1.3 on 2020-11-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20201119_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensortype',
            field=models.CharField(choices=[('led', 'LED'), ('weight', 'WEIGHT'), ('camera', 'CAMERA'), ('servo', 'SERVO')], default='Undefined', max_length=20),
        ),
    ]
