# Generated by Django 3.1.3 on 2020-11-19 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_house_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.room'),
            preserve_default=False,
        ),
    ]
