# Generated by Django 3.1.3 on 2020-11-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_sensor_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='ssidsensor',
            new_name='idsensor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='ssid',
        ),
    ]
