# Generated by Django 3.1.3 on 2020-11-20 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20201119_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='gpio',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
