# Generated by Django 3.1.3 on 2020-11-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_sensor_gpio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Home',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='house',
            new_name='home',
        ),
    ]
