# Generated by Django 3.1.3 on 2020-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20201121_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='testing',
            field=models.BooleanField(default=True),
        ),
    ]
