# Generated by Django 3.1.3 on 2020-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_room_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('bedroom', 'BEDROOM'), ('garage', 'GARAGE'), ('kitchen', 'KITCHEN'), ('living', 'LIVING ROOM')], default='bedroom', max_length=20),
        ),
    ]
