# Generated by Django 3.1.3 on 2020-12-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='iOS',
            field=models.BooleanField(default=True),
        ),
    ]
