# Generated by Django 3.1.3 on 2020-12-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_sensor_ios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='iOS',
            new_name='ios',
        ),
    ]
