# Generated by Django 3.1.3 on 2020-12-22 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20201207_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='atuador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='gpio',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensortype',
            field=models.CharField(choices=[('led', 'LED'), ('plug', 'PLUG'), ('camera', 'CAMERA'), ('servo', 'SERVO'), ('motion', 'MOTION')], default='Undefined', max_length=20),
        ),
    ]
