# Generated by Django 3.1.3 on 2020-12-22 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20201222_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='gpio',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
    ]
