# Generated by Django 3.1.3 on 2020-12-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
