# Generated by Django 3.1.3 on 2020-12-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='geo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
