# Generated by Django 3.1.3 on 2020-12-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_home_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.home'),
        ),
    ]
