# Generated by Django 3.1.3 on 2020-12-30 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_auto_20201228_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensors', models.ManyToManyField(blank=True, null=True, to='server.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.favourite'),
        ),
    ]
