# Generated by Django 3.1.3 on 2020-12-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_auto_20201230_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='server.Sensor'),
        ),
    ]
