# Generated by Django 3.1.3 on 2020-12-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_auto_20201230_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='server.Sensor'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
