# Generated by Django 3.1.3 on 2020-12-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20201230_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='server.Sensor'),
        ),
    ]
