# Generated by Django 3.1.3 on 2020-12-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20201230_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.sensor', unique=True),
        ),
    ]
