# Generated by Django 3.1.3 on 2020-12-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_auto_20201230_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.sensor'),
        ),
    ]
