# Generated by Django 3.1.3 on 2020-12-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_auto_20201230_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.home'),
        ),
    ]
