# Generated by Django 3.1.3 on 2020-12-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_vehicle_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='cor',
            new_name='modelo',
        ),
    ]
