# Generated by Django 3.1.3 on 2020-12-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_auto_20201230_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='matrícula',
            new_name='licenseplate',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='ano',
            new_name='year',
        ),
    ]
