# Generated by Django 3.1.3 on 2021-01-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='home',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.home'),
        ),
    ]
